interface Article {
  id: string;
  title: string;
  category: 'science' | 'home' | 'diet' | 'travel' | 'waste';
  excerpt: string;
  content: string;
  readTime: string;
}

const ARTICLES: Article[] = [
  {
    id: 'co2_basics',
    title: 'Demystifying CO2e: What is a Carbon Footprint?',
    category: 'science',
    excerpt: 'Understand greenhouse gases, carbon dioxide equivalents (CO2e), and how everyday activities affect global climate systems.',
    readTime: '5 min read',
    content: `
      <p>A <strong>carbon footprint</strong> is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. To simplify comparisons, scientists use <strong>CO2e</strong> (carbon dioxide equivalent), which translates different gases into the equivalent warming effect of carbon dioxide.</p>
      <br>
      <h4>Why is it critical?</h4>
      <p>Human activities, primarily the combustion of fossil fuels for transport and electricity, have raised atmospheric CO2 concentrations to levels unseen in millions of years. This traps heat in the biosphere, causing rising global temperatures, severe weather, and ecosystem disruption.</p>
      <br>
      <h4>The 1.5°C Goal</h4>
      <p>Under the Paris Climate Accord, countries committed to limiting global warming to 1.5°C above pre-industrial levels. To achieve this, the global average footprint per person must drop from over 4.5 tonnes annually to under <strong>2 tonnes (2,000 kg)</strong> by 2030, eventually reaching net zero.</p>
    `
  },
  {
    id: 'phantom_load',
    title: 'Unplugging Phantom Load: Home Energy Secrets',
    category: 'home',
    excerpt: 'Learn how household devices in standby mode consume substantial electricity, and how simple changes save emissions and costs.',
    readTime: '3 min read',
    content: `
      <p>Did you know that appliances draw electricity even when turned off? This is known as <strong>phantom load</strong>, vampire power, or standby consumption.</p>
      <br>
      <h4>The Cost of Standing By</h4>
      <p>Microwaves, television sets, chargers, game consoles, and computers plugged into walls consume power 24/7 to maintain internal clocks or standby lights. Standby power accounts for up to 10% of average household electricity bills, emitting hundreds of kilograms of carbon annually per home.</p>
      <br>
      <h4>Action Checklist:</h4>
      <ul>
        <li><strong>Use Smart Power Strips:</strong> These automatically cut off power to peripherals when the main device (like a TV or computer) is shut down.</li>
        <li><strong>Unplug Active Chargers:</strong> Laptop and mobile chargers draw small currents even when not connected to devices. Unplug them when finished.</li>
        <li><strong>Lower Heating Thermostats:</strong> Reducing household heating by just 1°C can decrease energy usage by 8% to 10% annually.</li>
      </ul>
    `
  },
  {
    id: 'diet_index',
    title: 'Dietary Footprints: Eating for the Planet',
    category: 'diet',
    excerpt: 'Explore how plant-focused eating habits significantly reduce carbon emissions compared to traditional meat-heavy diets.',
    readTime: '4 min read',
    content: `
      <p>Food production is responsible for roughly 26% of global greenhouse gas emissions. However, the emissions footprint varies drastically depending on what we choose to eat.</p>
      <br>
      <h4>The Protein Footprint Gap</h4>
      <p>Livestock agriculture, particularly beef and lamb production, requires vast tracts of land and emits methane (a greenhouse gas 28 times more potent than CO2). Producing 1 kg of beef generates approximately 60 kg of CO2e. In contrast, producing 1 kg of peas generates less than 1 kg of CO2e.</p>
      <br>
      <h4>Comparing Diet Profiles (Annual Average):</h4>
      <ul>
        <li><strong>Heavy Meat Diet:</strong> ~2,900 kg CO2e / year</li>
        <li><strong>Average Balanced Diet:</strong> ~2,000 kg CO2e / year</li>
        <li><strong>Vegetarian Diet:</strong> ~1,300 kg CO2e / year</li>
        <li><strong>Vegan Diet:</strong> ~900 kg CO2e / year</li>
      </ul>
      <br>
      <p>By introducing just 2 or 3 meat-free days weekly, you can reduce your personal diet emissions by hundreds of kilograms without fully transitioning to veganism.</p>
    `
  },
  {
    id: 'active_travel',
    title: 'Active Mobility: Ramping Down Transit Emissions',
    category: 'travel',
    excerpt: 'Discover the relative footprint of cars, mass transits, trains, and active travel, and how to structure your commute efficiently.',
    readTime: '4 min read',
    content: `
      <p>Transportation accounts for approximately one-fifth of global carbon emissions, with road transport (passenger vehicles and freight trucks) making up the vast majority.</p>
      <br>
      <h4>Relative Impact per Passenger-Kilometer:</h4>
      <ul>
        <li><strong>Petrol Car (Average):</strong> 180g CO2e / km</li>
        <li><strong>Diesel Car (Average):</strong> 170g CO2e / km</li>
        <li><strong>Hybrid Vehicle:</strong> 100g CO2e / km</li>
        <li><strong>Electric Vehicle (EV):</strong> 50g CO2e / km (based on average grid generation mix)</li>
        <li><strong>Public Bus / Metro Rail:</strong> 40g to 60g CO2e / km</li>
        <li><strong>Bicycle / Walking:</strong> 0g CO2e / km (zero operational emissions!)</li>
      </ul>
      <br>
      <h4>Active Commuting Strategy</h4>
      <p>Walking or bicycling for trips under 3 km improves physical health and avoids cold-engine emissions. For longer commutes, ridesharing (carpooling) or leveraging mass transit offers rapid, cumulative emissions reductions.</p>
    `
  },
  {
    id: 'recycle_myth',
    title: 'The Circular Economy: Beyond Simple Recycling',
    category: 'waste',
    excerpt: 'Recycling is a start, but reducing packaging, composting organics, and circular consumption are the true paths to zero-waste.',
    readTime: '5 min read',
    content: `
      <p>When organic waste is buried in landfills, it decomposes anaerobically (without oxygen) and produces <strong>methane gas</strong>. Furthermore, manufacturing brand-new products from virgin resources generates substantial carbon.</p>
      <br>
      <h4>The Waste Hierarchy</h4>
      <p>Recycling is only the third step. To achieve a zero-waste lifestyle, we must prioritize:</p>
      <ol>
        <li><strong>Refuse & Reduce:</strong> Avoid single-use plastics and over-packaged goods. Purchase only what you need.</li>
        <li><strong>Reuse & Repair:</strong> Mend clothing, repair electronics, and repurpose glass containers.</li>
        <li><strong>Recycle:</strong> Properly sort cardboards, plastics (PET/HDPE), glass, and metals to return materials to manufacturing loops.</li>
        <li><strong>Rot (Compost):</strong> Compost kitchen organic scraps. Composting occurs aerobically, returning carbon to soil as nutrients instead of venting methane into the sky.</li>
      </ol>
    `
  }
];

export function renderLearnHub(): void {
  const viewport = document.getElementById('app-viewport');
  if (!viewport) return;
  const vp = viewport;

  let activeCategory = 'all';
  let searchQuery = '';

  function renderView(): void {
    // Filter articles by category and search term
    const filteredArticles = ARTICLES.filter(art => {
      const matchesCategory = activeCategory === 'all' || art.category === activeCategory;
      const matchesSearch = art.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            art.excerpt.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });

    vp.innerHTML = `
      <div class="section-title-wrapper">
        <h2>Climate Resource Hub</h2>
        <p class="section-subtitle">Read bite-sized scientific articles and home guides to build your eco-literacy.</p>
      </div>

      <div class="glass-card mb-4" style="padding: 20px 28px;">
        <div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: center; justify-content: space-between;">
          
          <!-- Filter Tabs -->
          <div class="habits-filter-bar" style="margin-bottom: 0;">
            <button class="filter-btn ${activeCategory === 'all' ? 'active' : ''}" data-cat="all">All Topics</button>
            <button class="filter-btn ${activeCategory === 'science' ? 'active' : ''}" data-cat="science">Carbon Science</button>
            <button class="filter-btn ${activeCategory === 'home' ? 'active' : ''}" data-cat="home">Home Energy</button>
            <button class="filter-btn ${activeCategory === 'diet' ? 'active' : ''}" data-cat="diet">Eco-Diet</button>
            <button class="filter-btn ${activeCategory === 'travel' ? 'active' : ''}" data-cat="travel">Green Travel</button>
            <button class="filter-btn ${activeCategory === 'waste' ? 'active' : ''}" data-cat="waste">Zero Waste</button>
          </div>

          <!-- Search Input -->
          <div style="position: relative; width: 260px;">
            <input type="text" class="form-control" id="search-articles" placeholder="Search resources..." value="${searchQuery}" style="padding-right: 36px; border-radius: 20px;" aria-label="Search articles">
            <span style="position: absolute; right: 12px; top: 50%; transform: translateY(-50%); opacity: 0.5; pointer-events: none;">🔍</span>
          </div>

        </div>
      </div>

      <!-- Articles Grid -->
      <div class="learn-grid">
        ${filteredArticles.length === 0 ? `
          <div class="glass-card widget-span-12 text-center text-muted-color" style="padding: 40px 0; grid-column: 1 / -1;">
            <div style="font-size: 44px; margin-bottom: 12px;">📚</div>
            <p>No articles match your search criteria. Try removing filters.</p>
          </div>
        ` : filteredArticles.map(art => `
          <div class="glass-card article-card" data-article-id="${art.id}">
            <div class="article-header">
              <span>${art.category.toUpperCase()}</span>
              <span>${art.readTime}</span>
            </div>
            <h3 class="article-title">${art.title}</h3>
            <p class="article-excerpt">${art.excerpt}</p>
            
            <button class="btn btn-secondary mt-4 btn-read-article" style="padding: 8px 16px; font-size: 13px; font-weight: 600;">
              Read Guide &rarr;
            </button>
          </div>
        `).join('')}
      </div>
    `;

    bindLearnListeners();
  }

  function bindLearnListeners(): void {
    // Category click triggers
    const categoryBtns = vp.querySelectorAll('.filter-btn');
    categoryBtns.forEach(btn => {
      btn.addEventListener('click', () => {
        const cat = btn.getAttribute('data-cat');
        if (cat) {
          activeCategory = cat;
          renderView();
        }
      });
    });

    // Search query keyup
    const searchInput = document.getElementById('search-articles') as HTMLInputElement;
    searchInput?.addEventListener('input', () => {
      searchQuery = searchInput.value;
      
      // Delay render slightly to avoid laggy inputs
      setTimeout(() => {
        // Double check input hasn't changed in the mean time
        if (searchInput.value === searchQuery) {
          // Re-render only list part or full view. Since it is quick, full render is fine
          // but we want cursor focus to persist. We can handle search focus recovery:
          const caretPos = searchInput.selectionStart;
          renderView();
          const newSearchInput = document.getElementById('search-articles') as HTMLInputElement;
          if (newSearchInput) {
            newSearchInput.focus();
            newSearchInput.setSelectionRange(caretPos, caretPos);
          }
        }
      }, 250);
    });

    // Read full article triggers
    const readBtns = vp.querySelectorAll('.btn-read-article');
    readBtns.forEach(btn => {
      const card = btn.closest('.article-card');
      const articleId = card?.getAttribute('data-article-id');
      
      btn.addEventListener('click', () => {
        if (articleId) showArticleModal(articleId, btn as HTMLElement);
      });
    });
  }

  function showArticleModal(id: string, triggerEl: HTMLElement): void {
    const article = ARTICLES.find(a => a.id === id);
    if (!article) return;

    const modalContainer = document.getElementById('modal-container');
    if (!modalContainer) return;

    modalContainer.innerHTML = `
      <div class="modal-content" style="max-width: 650px; text-align: left; max-height: 85vh; overflow-y: auto;">
        <button class="modal-close" id="btn-close-article" style="position: sticky; top: 0; float: right;" aria-label="Close Article">&times;</button>
        
        <div style="font-size: 11px; text-transform: uppercase; font-weight: 700; color: var(--primary-light); margin-bottom: 8px;">
          ${article.category.toUpperCase()} • ${article.readTime}
        </div>
        
        <h2 style="font-size: 24px; margin-bottom: 20px; line-height: 1.3;">
          ${article.title}
        </h2>

        <div style="line-height: 1.6; font-size: 14.5px; color: var(--text-secondary);">
          ${article.content}
        </div>

        <div style="margin-top: 30px; border-top: 1px solid var(--border-glass); padding-top: 20px; text-align: right;">
          <button class="btn btn-primary" id="btn-article-ok" style="padding: 10px 20px;">Got It!</button>
        </div>
      </div>
    `;

    modalContainer.classList.remove('hidden');
    // Shift focus to the close button for accessibility
    setTimeout(() => {
      document.getElementById('btn-close-article')?.focus();
    }, 50);

    const closeModal = () => {
      modalContainer.classList.add('hidden');
      triggerEl.focus(); // Return focus to opening button
    };

    document.getElementById('btn-close-article')?.addEventListener('click', closeModal);
    document.getElementById('btn-article-ok')?.addEventListener('click', closeModal);
    modalContainer.addEventListener('click', (e) => {
      if (e.target === modalContainer) closeModal();
    });
  }

  renderView();
}
